apiVersion: apps/v1
kind: Deployment
metadata:
  name: modbus
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: modbus
  template:
    metadata:
      labels:
        app: modbus
    spec:
      hostNetwork: true
      nodeName: kedge1 # Schedule the Pod to the node kedge1. Please modify
      containers:
        - name: modbus
          image: modbus:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: data-volume          
              mountPath: /etc/data
          command: ["./main"]
      volumes:
        - name: data-volume              
          hostPath:
            path: /etc/data              
            type: DirectoryOrCreate
      restartPolicy: Always
