name: Deploy Nginx to Kubeadm Cluster on GCP

on:
  push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nginx-app:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/nginx-app:latest

      - name: Set up Kubeconfig
        env:
          KUBECONFIG: $HOME/.kube/config
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $KUBECONFIG
          chmod 600 $KUBECONFIG

      - name: Apply Nginx Deployment to Kubernetes
        run: |
          kubectl apply -f nginx-deployment.yml
          
      - name: Update Nginx Image in Kubernetes Deployment
        run: |
          kubectl set image deployment/nginx-deployment nginx=${{ secrets.DOCKER_USERNAME }}/nginx-app:latest
          kubectl rollout status deployment/nginx-deployment
