name: Deploy to Kubeadm Cluster on GCP

on:
  push:
    branches: [ "LayaMoorthy-170673-patch-1" ]
  pull_request:
    branches: [ "LayaMoorthy-170673-patch-1" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4  # Set up Go environment
        with:
          go-version: '1.19'       # Adjust this to your Go version

    #  - name: List Files for Debugging
    #    run: ls -R
      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Go Application
        run: |
          cd ./kubeedge-counter-demo/web-controller-app
          make clean
          make all
          #ls -al
          cat Makefile
          make docker
   
      - name: Set up Kubeconfig
       # env:
       #   KUBECONFIG: $HOME/.kube/config
        run: |
          mkdir -p $HOME/.kube  
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > ${HOME}/.kube/config
          chmod 600 ${HOME}/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/myapp-deployment myapp-container=${{ secrets.DOCKER_USERNAME }}/myapp:latest
          kubectl rollout status deployment/myapp-deployment
