name: Deploy to Kubeadm Cluster on GCP

on:
  push:
    branches: [ "LayaMoorthy-170673-patch-1" ]
  pull_request:
    branches: [ "LayaMoorthy-170673-patch-1" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Set up Go
      #   uses: actions/setup-go@v4  # Set up Go environment
      #   with:
      #     go-version: '1.19'       # Adjust this to your Go version

    #  - name: List Files for Debugging
    #    run: ls -R
      # - name: Docker Login
      #   run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # - name: Build Go Application
      #   run: |
      #     cd ./kubeedge-counter-demo/web-controller-app
      #     make clean
      #     make all
      #     #ls -al
      #     cat Makefile
      #     make docker

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.31.2'  

      - name: Set up Kubeconfig

        run: |
          mkdir -p $HOME/.kube  
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > ${HOME}/.kube/config
          chmod 600 ${HOME}/.kube/config

      - name: Deploy to Kubernetes
        env:
          K8S_TOKEN: ${{ secrets.K8S_TOKEN }}
        run: |
          kubectl apply -f nginx.yaml
        
      # - name: Set up Kubeconfig

      #   run: |
      #     mkdir -p $HOME/.kube  
      #     echo "${{ secrets.KUBECONFIG }}" | base64 --decode > ${HOME}/.kube/config
      #     chmod 600 ${HOME}/.kube/config

      # - name: Set the Kubernetes context
      #   uses: azure/k8s-set-context@v2
      #   with:
      #     method: service-account
      #     k8s-url: https://10.128.0.34:6443
      #     k8s-secret: ${{ secrets.KUBERNETES_SECRET }}

      # - name: Checkout source code
      #   uses: actions/checkout@v3
      # - name: View kubectl configuration
      #   run: |
      #     kubectl config use-context master
      #     kubectl config view --minify
      # - name: Deploy to the Kubernetes cluster
      #   uses: azure/k8s-deploy@v1
      #   with:
      #     namespace: default
      #     manifests: |
      #       nginx.yaml

           

      # - name: Set up Kubectl
      #   uses: azure/k8s-set-context@v1
      #   with:
      #     kubeconfig: ${{ secrets.KUBECONFIG }}

          
 
      # - name: Deploy to Kubernetes
        # run: |
        #   kubectl get nodes

        #  kubectl set image deployment/myapp-deployment myapp-container=${{ secrets.DOCKER_USERNAME }}/myapp:latest
        #  kubectl rollout status deployment/myapp-deployment
