name: Deploy to Kubeadm Cluster on GCP

on:
  push:
    branches: [ "LayaMoorthy-170673-patch-1" ]
  pull_request:
    branches: [ "LayaMoorthy-170673-patch-1" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4  # Set up Go environment
        with:
          go-version: '1.19'       # Adjust this to your Go version

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Go Application
        run: |
          cd ./kubeedge-counter-demo/web-controller-app
          make clean
          make all
          #ls -al
          cat Makefile
          make docker
          cd ../counter-mapper
          make clean
          make all
          ls -al
          cat Makefile
          make docker
          

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.31.2'  

      - name: Set up Kubeconfig

        run: |
          mkdir -p $HOME/.kube  
          echo "${{ secrets.KUBECONFIG }}"  > ${HOME}/.kube/config
          chmod 600 ${HOME}/.kube/config

      - name: Deploy to Kubernetes
     #   env:
    #      K8S_TOKEN: ${{ secrets.K8S_TOKEN }}
        run: |
          kubectl apply -f kubeedge-counter-demo/crds/kubeedge-web-controller-app.yaml --validate=false --insecure-skip-tls-verify
          kubectl apply -f kubeedge-counter-demo/crds/kubeedge-pi-counter-app.yaml --validate=false --insecure-skip-tls-verify
        

 
    
