name: Deploy to Kubeadm Cluster on GCP

on:
  push:
    branches: [ "LayaMoorthy-170673-patch-1" ]
  pull_request:
    branches: [ "LayaMoorthy-170673-patch-1" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go and Build & Push Docker Image
        uses: actions/setup-go@v4  # Set up Go environment
        with:
          go-version: '1.19'       # Adjust this to your Go version

      - name: List Files for Debugging
        run: ls -R

      - name: Build Go Application
        run: |
          cd ./kubeedge-counter-demo/web-controller-app
          make all

      - name: Build and Push Docker Image
        run: |
          cd ./kubeedge-counter-demo/web-controller-app
          make docker


      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: layamoorthy170673/demo-app
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Kubeconfig
        env:
          KUBECONFIG: $HOME/.kube/config
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $KUBECONFIG
          chmod 600 $KUBECONFIG

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/myapp-deployment myapp-container=${{ secrets.DOCKER_USERNAME }}/myapp:latest
          kubectl rollout status deployment/myapp-deployment
